### ISSUE TITLE
Compiled Solutions

### ISSUE THREAD

**Issue by EHCanadian** [lunarmodules/luasec#151]
Anyone have a public compiled luasocket 2.0.2+ and luasec libraries for x86 or x64 under windows 7+

**Comment by pkulchenko** [comment]
I have them compiled for Lua 5.1 available here: https://download.zerobrane.com/misc/luasec-0.8-openssl-1.1.1c-luasocket-3.0-win64.zip and https://download.zerobrane.com/misc/luasec-0.8-openssl-1.1.1c-luasocket-3.0-win32.zip. I also have a bit newer version of openssl compiled for Lua 5.1-5.3, but only for win32 (see the content of clibs, clibs52, and clibs53 folders in this branch: https://github.com/pkulchenko/ZeroBraneStudio/tree/luasec-0.9-openssl-1.1.1d-64bit/bin).

**Comment by stefanak-michal** [comment]
Please, can we get actual?

**Comment by alerque** [comment]
Duplicate of #115.
