### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by danzfairs** [lunarmodules/luasec#166]
I'm seeing an error in ssl.lua when I try to import it into my script:

/usr/local/share/lua/5.2/ssl.lua: invalid ELF header.

![2021-02-10 14_22_11-Greenshot image editor](https://user-images.githubusercontent.com/62962866/107573967-6d2a4b00-6bab-11eb-803c-e8e7cfb71efa.png)

**Comment by daurnimator** [comment]
Looks like you confused LUA_CPATH with LUA_PATH
